version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run: npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "40:9e:ee:20:69:ec:87:26:14:3e:6d:11:07:cc:b9:10"
      - run:
          name: Install rsync
          command: sudo apt install rsync -y
      - run:
          name: Deploy front to server
          command: |
            rsync -avHr ~/repo/public/ -e ssh rodrigo@104.196.160.41:/apps/WeebBot-Admin/public
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master